# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vk-crawler.ui'
#
# Created: Sat May 18 22:02:26 2013
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(619, 629)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 611, 572))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.saveToFolderLineEdit = QtGui.QLineEdit(self.tab)
        self.saveToFolderLineEdit.setObjectName(_fromUtf8("saveToFolderLineEdit"))
        self.gridLayout.addWidget(self.saveToFolderLineEdit, 1, 1, 1, 1)
        self.linkToTargetLineEdit = QtGui.QLineEdit(self.tab)
        self.linkToTargetLineEdit.setInputMask(_fromUtf8(""))
        self.linkToTargetLineEdit.setObjectName(_fromUtf8("linkToTargetLineEdit"))
        self.gridLayout.addWidget(self.linkToTargetLineEdit, 0, 1, 1, 2)
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.chooseSaveFolderButton = QtGui.QPushButton(self.tab)
        self.chooseSaveFolderButton.setObjectName(_fromUtf8("chooseSaveFolderButton"))
        self.gridLayout.addWidget(self.chooseSaveFolderButton, 1, 2, 1, 1)
        self.label = QtGui.QLabel(self.tab)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.albumsTableWidget = QtGui.QTableWidget(self.tab)
        self.albumsTableWidget.setObjectName(_fromUtf8("albumsTableWidget"))
        self.albumsTableWidget.setColumnCount(5)
        self.albumsTableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.albumsTableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.albumsTableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.albumsTableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.albumsTableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.albumsTableWidget.setHorizontalHeaderItem(4, item)
        self.albumsTableWidget.verticalHeader().setSortIndicatorShown(False)
        self.verticalLayout_2.addWidget(self.albumsTableWidget)
        self.picturesTableWidget = QtGui.QTableWidget(self.tab)
        self.picturesTableWidget.setMaximumSize(QtCore.QSize(587, 192))
        self.picturesTableWidget.setObjectName(_fromUtf8("picturesTableWidget"))
        self.picturesTableWidget.setColumnCount(5)
        self.picturesTableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.picturesTableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.picturesTableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.picturesTableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.picturesTableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.picturesTableWidget.setHorizontalHeaderItem(4, item)
        self.verticalLayout_2.addWidget(self.picturesTableWidget)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.selectAllButton = QtGui.QPushButton(self.tab)
        self.selectAllButton.setObjectName(_fromUtf8("selectAllButton"))
        self.horizontalLayout.addWidget(self.selectAllButton)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.downloadButton = QtGui.QPushButton(self.tab)
        self.downloadButton.setObjectName(_fromUtf8("downloadButton"))
        self.horizontalLayout.addWidget(self.downloadButton)
        self.scanButton = QtGui.QPushButton(self.tab)
        self.scanButton.setObjectName(_fromUtf8("scanButton"))
        self.horizontalLayout.addWidget(self.scanButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.progressBar = QtGui.QProgressBar(self.tab)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.verticalLayout.addWidget(self.progressBar)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 619, 27))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuOptions = QtGui.QMenu(self.menubar)
        self.menuOptions.setObjectName(_fromUtf8("menuOptions"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionCredentials = QtGui.QAction(MainWindow)
        self.actionCredentials.setObjectName(_fromUtf8("actionCredentials"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.menuOptions.addAction(self.actionCredentials)
        self.menuHelp.addAction(self.actionAbout)
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuOptions.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.saveToFolderLineEdit.setPlaceholderText(_translate("MainWindow", "your downloaded files will be saved here", None))
        self.linkToTargetLineEdit.setPlaceholderText(_translate("MainWindow", "http://vk.com/id1234", None))
        self.label_2.setText(_translate("MainWindow", "Save to folder:", None))
        self.chooseSaveFolderButton.setText(_translate("MainWindow", "Choose", None))
        self.label.setText(_translate("MainWindow", "Link to target:", None))
        self.albumsTableWidget.setSortingEnabled(True)
        item = self.albumsTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "title", None))
        item = self.albumsTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "size", None))
        item = self.albumsTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "created", None))
        item = self.albumsTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "updated", None))
        item = self.albumsTableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "aid", None))
        item = self.picturesTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "src", None))
        item = self.picturesTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "album", None))
        item = self.picturesTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "created", None))
        item = self.picturesTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "owner_id", None))
        item = self.picturesTableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "progress", None))
        self.selectAllButton.setText(_translate("MainWindow", "Select all", None))
        self.downloadButton.setText(_translate("MainWindow", "Download", None))
        self.scanButton.setText(_translate("MainWindow", "Scan", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Download", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Upload", None))
        self.menuOptions.setTitle(_translate("MainWindow", "options", None))
        self.menuHelp.setTitle(_translate("MainWindow", "help", None))
        self.menuFile.setTitle(_translate("MainWindow", "file", None))
        self.actionCredentials.setText(_translate("MainWindow", "credentials", None))
        self.actionAbout.setText(_translate("MainWindow", "about", None))
        self.actionExit.setText(_translate("MainWindow", "exit", None))

